name: Build Windows EXE

on:
  push:
    branches: [main]
    tags:
      - 'v*'       
  workflow_dispatch:  

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt6 pymysql
        pip install --upgrade mysql-connector-python
        

    - name: Build .exe with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name HealthDashboard --hidden-import os --hidden-import pymysql --hidden-import mysql main.py


    - name: Check if .exe was created
      run: dir dist

    - name: Upload .exe to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/HealthDashboard.exe
          Database/gesundheit_dashboard.db
        tag_name: ${{ github.ref_name }}  # Use the tag that triggered the workflow
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_HEALTHDASHBOARD }}
